name: build-python-pandas

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write    # GHCR 푸시에 필요

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          # 만약 파일명이 'pythonDocker'라면 아래 줄을 사용하세요:
          # file: ./pythonDocker
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/python-pandas:1.0
            ghcr.io/${{ github.repository }}/python-pandas:latest
