name: build-python-pandas

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write   # GHCR 푸시에 필요

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 경로를 전부 소문자로 변환 (중요!)
      - name: Set lowercase image name
        run: |
          IMAGE="ghcr.io/${{ github.repository }}/python-pandas"
          echo "IMAGE_NAME=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          # Dockerfile 이름이 'pythonDocker'라면 아래 줄로 교체:
          # file: ./pythonDocker
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:1.0
            ${{ env.IMAGE_NAME }}:latest